// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofrinpikbxkhkwdvcawt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mcmlucGlrYnhraGt3ZHZjYXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTI4NzMsImV4cCI6MjA2ODYyODg3M30.4m2u4204lswTS9sobNmstZcfVX23Z693c19S3W7sdwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});